Upgrading to Bevy 0.12
ForesightMiningSoftwareCorporation/bevy_polyline pull request #52
Opened 2023-11-10 00:38 UTC by rszemplinski

Not saying the changes I made are the best way to make this work with Bevy `0.12` but they do compile and run. :sweat_smile:

2023-11-13 23:21 UTC, Shatur requested changes

2023-11-13 23:21 UTC, Shatur commented on .gitignore
> +.vscode
I would suggest to remove additional changes from this file.

2023-11-13 23:21 UTC, Shatur commented on examples/depth_bias.rs
> +        .add_plugins(LogDiagnosticsPlugin::default())
Why you includes these plugins into examples?

2023-11-13 23:21 UTC, Shatur commented on src/lib.rs
> +pub const SHADER_HANDLE: Handle<Shader> =
Could you use `embed_asset!`? See https://bevyengine.org/news/bevy-0-12/#embedded-assets

2023-11-13 23:21 UTC, Shatur commented on src/material.rs
> +            panic!();
Why do you panic here?

2023-11-17 22:39 UTC, Shatur requested changes

2023-11-17 22:39 UTC, Shatur commented on Cargo.toml
> +version = "0.14"
Could you set it to 0.13? This is what bevy use.

2024-01-26 18:50 UTC, IceSentry commented
closed by #53

2024-01-26 18:50 UTC, closed without merging